-- =====================================================================
-- 이력서(개인이력카드 + SKILL INVENTORY) DDL
-- DBMS : Oracle 12c 이상 (IDENTITY 컬럼 사용)
-- 원본 : ..\이력서.docx
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. 인적사항 (개인이력카드 상단)
-- ---------------------------------------------------------------------
CREATE TABLE RSM_PERSON (
    PERSON_ID       NUMBER GENERATED ALWAYS AS IDENTITY,
    PERSON_NM       VARCHAR2(50)   NOT NULL,
    BIRTH_DT        DATE,
    GENDER_CD       CHAR(1),
    COMPANY_NM      VARCHAR2(100),
    HIRE_DT         DATE,
    DEPT_NM         VARCHAR2(100),
    POSITION_NM     VARCHAR2(50),
    MILITARY_NM     VARCHAR2(50),
    PHONE_NO        VARCHAR2(20),
    EMAIL           VARCHAR2(100),
    ADDRESS         VARCHAR2(300),
    ETC_SW          VARCHAR2(1000),
    WRITER_NM       VARCHAR2(50),
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RSM_PERSON PRIMARY KEY (PERSON_ID),
    CONSTRAINT CK_RSM_PERSON_GENDER CHECK (GENDER_CD IN ('M', 'F'))
);

COMMENT ON TABLE  RSM_PERSON             IS '이력서 인적사항';
COMMENT ON COLUMN RSM_PERSON.PERSON_ID   IS '인적사항 ID';
COMMENT ON COLUMN RSM_PERSON.PERSON_NM   IS '성명';
COMMENT ON COLUMN RSM_PERSON.BIRTH_DT    IS '생년월일';
COMMENT ON COLUMN RSM_PERSON.GENDER_CD   IS '성별 (M:남, F:여)';
COMMENT ON COLUMN RSM_PERSON.COMPANY_NM  IS '소속회사';
COMMENT ON COLUMN RSM_PERSON.HIRE_DT     IS '입사일자';
COMMENT ON COLUMN RSM_PERSON.DEPT_NM     IS '부서';
COMMENT ON COLUMN RSM_PERSON.POSITION_NM IS '직위';
COMMENT ON COLUMN RSM_PERSON.MILITARY_NM IS '병적';
COMMENT ON COLUMN RSM_PERSON.PHONE_NO    IS '전화';
COMMENT ON COLUMN RSM_PERSON.EMAIL       IS 'E-Mail';
COMMENT ON COLUMN RSM_PERSON.ADDRESS     IS '주소';
COMMENT ON COLUMN RSM_PERSON.ETC_SW      IS '기타 (활용가능한 S/W 및 기법, FrameWork)';
COMMENT ON COLUMN RSM_PERSON.WRITER_NM   IS '작성자';
COMMENT ON COLUMN RSM_PERSON.CREATED_AT  IS '등록일시';

-- ---------------------------------------------------------------------
-- 2. 학력사항
-- ---------------------------------------------------------------------
CREATE TABLE RSM_EDUCATION (
    EDU_ID          NUMBER GENERATED ALWAYS AS IDENTITY,
    PERSON_ID       NUMBER         NOT NULL,
    SCHOOL_NM       VARCHAR2(100)  NOT NULL,
    MAJOR_NM        VARCHAR2(100),
    ADMISSION_DT    DATE,
    GRADUATION_DT   DATE,
    GRAD_STATUS     VARCHAR2(20),
    CONSTRAINT PK_RSM_EDUCATION PRIMARY KEY (EDU_ID),
    CONSTRAINT FK_RSM_EDUCATION_PERSON FOREIGN KEY (PERSON_ID)
        REFERENCES RSM_PERSON (PERSON_ID) ON DELETE CASCADE
);

COMMENT ON TABLE  RSM_EDUCATION               IS '학력사항';
COMMENT ON COLUMN RSM_EDUCATION.EDU_ID        IS '학력 ID';
COMMENT ON COLUMN RSM_EDUCATION.PERSON_ID     IS '인적사항 ID';
COMMENT ON COLUMN RSM_EDUCATION.SCHOOL_NM     IS '학교명';
COMMENT ON COLUMN RSM_EDUCATION.MAJOR_NM      IS '전공(계열)';
COMMENT ON COLUMN RSM_EDUCATION.ADMISSION_DT  IS '입학일자';
COMMENT ON COLUMN RSM_EDUCATION.GRADUATION_DT IS '졸업일자';
COMMENT ON COLUMN RSM_EDUCATION.GRAD_STATUS   IS '졸업구분 (졸업, 수료, 중퇴 등)';

-- ---------------------------------------------------------------------
-- 3. 자격증
-- ---------------------------------------------------------------------
CREATE TABLE RSM_CERTIFICATE (
    CERT_ID         NUMBER GENERATED ALWAYS AS IDENTITY,
    PERSON_ID       NUMBER         NOT NULL,
    CERT_NM         VARCHAR2(100)  NOT NULL,
    ACQUIRED_DT     DATE,
    CONSTRAINT PK_RSM_CERTIFICATE PRIMARY KEY (CERT_ID),
    CONSTRAINT FK_RSM_CERTIFICATE_PERSON FOREIGN KEY (PERSON_ID)
        REFERENCES RSM_PERSON (PERSON_ID) ON DELETE CASCADE
);

COMMENT ON TABLE  RSM_CERTIFICATE             IS '자격증';
COMMENT ON COLUMN RSM_CERTIFICATE.CERT_ID     IS '자격증 ID';
COMMENT ON COLUMN RSM_CERTIFICATE.PERSON_ID   IS '인적사항 ID';
COMMENT ON COLUMN RSM_CERTIFICATE.CERT_NM     IS '자격증명';
COMMENT ON COLUMN RSM_CERTIFICATE.ACQUIRED_DT IS '취득일';

-- ---------------------------------------------------------------------
-- 4. 경력사항 (회사명/기간/직위/담당업무)
-- ---------------------------------------------------------------------
CREATE TABLE RSM_CAREER (
    CAREER_ID       NUMBER GENERATED ALWAYS AS IDENTITY,
    PERSON_ID       NUMBER         NOT NULL,
    COMPANY_NM      VARCHAR2(100)  NOT NULL,
    START_DT        DATE           NOT NULL,
    END_DT          DATE,
    POSITION_NM     VARCHAR2(50),
    DUTY_DESC       VARCHAR2(500),
    CONSTRAINT PK_RSM_CAREER PRIMARY KEY (CAREER_ID),
    CONSTRAINT FK_RSM_CAREER_PERSON FOREIGN KEY (PERSON_ID)
        REFERENCES RSM_PERSON (PERSON_ID) ON DELETE CASCADE,
    CONSTRAINT CK_RSM_CAREER_PERIOD CHECK (END_DT IS NULL OR END_DT >= START_DT)
);

COMMENT ON TABLE  RSM_CAREER             IS '경력사항';
COMMENT ON COLUMN RSM_CAREER.CAREER_ID   IS '경력 ID';
COMMENT ON COLUMN RSM_CAREER.PERSON_ID   IS '인적사항 ID';
COMMENT ON COLUMN RSM_CAREER.COMPANY_NM  IS '회사명';
COMMENT ON COLUMN RSM_CAREER.START_DT    IS '근무 시작일';
COMMENT ON COLUMN RSM_CAREER.END_DT      IS '근무 종료일 (NULL = 재직중)';
COMMENT ON COLUMN RSM_CAREER.POSITION_NM IS '직위';
COMMENT ON COLUMN RSM_CAREER.DUTY_DESC   IS '담당업무';

-- ---------------------------------------------------------------------
-- 5. 교육이수
-- ---------------------------------------------------------------------
CREATE TABLE RSM_TRAINING (
    TRAINING_ID     NUMBER GENERATED ALWAYS AS IDENTITY,
    PERSON_ID       NUMBER         NOT NULL,
    COURSE_NM       VARCHAR2(200)  NOT NULL,
    START_DT        DATE,
    END_DT          DATE,
    INSTITUTION_NM  VARCHAR2(100),
    CONSTRAINT PK_RSM_TRAINING PRIMARY KEY (TRAINING_ID),
    CONSTRAINT FK_RSM_TRAINING_PERSON FOREIGN KEY (PERSON_ID)
        REFERENCES RSM_PERSON (PERSON_ID) ON DELETE CASCADE,
    CONSTRAINT CK_RSM_TRAINING_PERIOD CHECK (END_DT IS NULL OR START_DT IS NULL OR END_DT >= START_DT)
);

COMMENT ON TABLE  RSM_TRAINING                IS '교육이수';
COMMENT ON COLUMN RSM_TRAINING.TRAINING_ID    IS '교육 ID';
COMMENT ON COLUMN RSM_TRAINING.PERSON_ID      IS '인적사항 ID';
COMMENT ON COLUMN RSM_TRAINING.COURSE_NM      IS '교육명';
COMMENT ON COLUMN RSM_TRAINING.START_DT       IS '시작일';
COMMENT ON COLUMN RSM_TRAINING.END_DT         IS '종료일';
COMMENT ON COLUMN RSM_TRAINING.INSTITUTION_NM IS '교육기관';

-- ---------------------------------------------------------------------
-- 6. 보유기술 및 외국어능력
-- ---------------------------------------------------------------------
CREATE TABLE RSM_SKILL (
    SKILL_ID        NUMBER GENERATED ALWAYS AS IDENTITY,
    PERSON_ID       NUMBER         NOT NULL,
    SKILL_NM        VARCHAR2(100)  NOT NULL,
    PROFICIENCY     CHAR(1),
    CONSTRAINT PK_RSM_SKILL PRIMARY KEY (SKILL_ID),
    CONSTRAINT FK_RSM_SKILL_PERSON FOREIGN KEY (PERSON_ID)
        REFERENCES RSM_PERSON (PERSON_ID) ON DELETE CASCADE,
    CONSTRAINT UK_RSM_SKILL UNIQUE (PERSON_ID, SKILL_NM),
    CONSTRAINT CK_RSM_SKILL_PROFICIENCY CHECK (PROFICIENCY IN ('A', 'B', 'C'))
);

COMMENT ON TABLE  RSM_SKILL             IS '보유기술 및 외국어능력';
COMMENT ON COLUMN RSM_SKILL.SKILL_ID    IS '보유기술 ID';
COMMENT ON COLUMN RSM_SKILL.PERSON_ID   IS '인적사항 ID';
COMMENT ON COLUMN RSM_SKILL.SKILL_NM    IS '기술/외국어명';
COMMENT ON COLUMN RSM_SKILL.PROFICIENCY IS '숙련도 (A, B, C)';

-- ---------------------------------------------------------------------
-- 7. 프로젝트 이력 (SKILL INVENTORY)
-- ---------------------------------------------------------------------
CREATE TABLE RSM_PROJECT (
    PROJECT_ID      NUMBER GENERATED ALWAYS AS IDENTITY,
    PERSON_ID       NUMBER         NOT NULL,
    PROJECT_NM      VARCHAR2(300)  NOT NULL,
    START_DT        DATE           NOT NULL,
    END_DT          DATE,
    CLIENT_NM       VARCHAR2(100),
    WORK_COMPANY_NM VARCHAR2(100),
    ROLE_NM         VARCHAR2(50),
    ENV_MODEL       VARCHAR2(200),
    ENV_OS          VARCHAR2(200),
    ENV_LANGUAGE    VARCHAR2(200),
    ENV_DBMS        VARCHAR2(200),
    ENV_TOOL        VARCHAR2(200),
    ENV_COMM        VARCHAR2(200),
    ENV_WAS         VARCHAR2(200),
    TASK_DESC       VARCHAR2(2000),
    CONSTRAINT PK_RSM_PROJECT PRIMARY KEY (PROJECT_ID),
    CONSTRAINT FK_RSM_PROJECT_PERSON FOREIGN KEY (PERSON_ID)
        REFERENCES RSM_PERSON (PERSON_ID) ON DELETE CASCADE,
    CONSTRAINT CK_RSM_PROJECT_PERIOD CHECK (END_DT IS NULL OR END_DT >= START_DT)
);

COMMENT ON TABLE  RSM_PROJECT                 IS '프로젝트 이력 (SKILL INVENTORY)';
COMMENT ON COLUMN RSM_PROJECT.PROJECT_ID      IS '프로젝트 ID';
COMMENT ON COLUMN RSM_PROJECT.PERSON_ID       IS '인적사항 ID';
COMMENT ON COLUMN RSM_PROJECT.PROJECT_NM      IS '프로젝트명 (시스템명)';
COMMENT ON COLUMN RSM_PROJECT.START_DT        IS '참여 시작일';
COMMENT ON COLUMN RSM_PROJECT.END_DT          IS '참여 종료일';
COMMENT ON COLUMN RSM_PROJECT.CLIENT_NM       IS '고객사';
COMMENT ON COLUMN RSM_PROJECT.WORK_COMPANY_NM IS '근무회사';
COMMENT ON COLUMN RSM_PROJECT.ROLE_NM         IS '역할';
COMMENT ON COLUMN RSM_PROJECT.ENV_MODEL       IS '개발환경 - 기종';
COMMENT ON COLUMN RSM_PROJECT.ENV_OS          IS '개발환경 - OS';
COMMENT ON COLUMN RSM_PROJECT.ENV_LANGUAGE    IS '개발환경 - 언어';
COMMENT ON COLUMN RSM_PROJECT.ENV_DBMS        IS '개발환경 - DBMS';
COMMENT ON COLUMN RSM_PROJECT.ENV_TOOL        IS '개발환경 - TOOL';
COMMENT ON COLUMN RSM_PROJECT.ENV_COMM        IS '개발환경 - 통신';
COMMENT ON COLUMN RSM_PROJECT.ENV_WAS         IS '개발환경 - WAS';
COMMENT ON COLUMN RSM_PROJECT.TASK_DESC       IS '수행업무';

-- ---------------------------------------------------------------------
-- 인덱스 (FK 조회용)
-- ---------------------------------------------------------------------
CREATE INDEX IX_RSM_EDUCATION_PERSON   ON RSM_EDUCATION   (PERSON_ID);
CREATE INDEX IX_RSM_CERTIFICATE_PERSON ON RSM_CERTIFICATE (PERSON_ID);
CREATE INDEX IX_RSM_CAREER_PERSON      ON RSM_CAREER      (PERSON_ID);
CREATE INDEX IX_RSM_TRAINING_PERSON    ON RSM_TRAINING    (PERSON_ID);
CREATE INDEX IX_RSM_PROJECT_PERSON     ON RSM_PROJECT     (PERSON_ID);
-- RSM_SKILL 은 UK_RSM_SKILL(PERSON_ID, SKILL_NM) 인덱스로 대체
