-- ============================================================
-- 개인이력카드 / SKILL INVENTORY  (원본: 이력서.docx)
-- DBMS : Oracle 12c 이상 (IDENTITY 컬럼 사용)
-- ============================================================

-- 재실행용 삭제 (자식 -> 부모 순)
BEGIN
  FOR t IN (SELECT column_value AS name FROM TABLE(sys.odcivarchar2list(
              'RESUME_PROJECT','RESUME_SKILL','RESUME_TRAINING','RESUME_CAREER',
              'RESUME_CERTIFICATION','RESUME_EDUCATION','RESUME_EMPLOYEE'))) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.name || ' CASCADE CONSTRAINTS PURGE';
    EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
    END;
  END LOOP;
END;
/

-- 1. 인적사항 (개인이력카드 상단)
CREATE TABLE RESUME_EMPLOYEE (
  EMP_ID          NUMBER GENERATED ALWAYS AS IDENTITY,
  EMP_NAME        VARCHAR2(50)  NOT NULL,
  BIRTH_DATE      DATE,
  GENDER          CHAR(1),
  COMPANY_NAME    VARCHAR2(100),
  JOIN_DATE       DATE,
  DEPARTMENT      VARCHAR2(100),
  POSITION_TITLE  VARCHAR2(50),
  MILITARY_STATUS VARCHAR2(50),
  PHONE           VARCHAR2(30),
  EMAIL           VARCHAR2(100),
  ADDRESS         VARCHAR2(300),
  OTHER_SW        VARCHAR2(500),
  CONSTRAINT PK_RESUME_EMPLOYEE PRIMARY KEY (EMP_ID),
  CONSTRAINT CK_RESUME_EMP_GENDER CHECK (GENDER IN ('M','F'))
);

-- 2. 학력사항
CREATE TABLE RESUME_EDUCATION (
  EDU_ID       NUMBER GENERATED ALWAYS AS IDENTITY,
  EMP_ID       NUMBER        NOT NULL,
  SCHOOL_NAME  VARCHAR2(100) NOT NULL,
  MAJOR        VARCHAR2(100),
  ENTER_DATE   DATE,
  GRAD_DATE    DATE,
  GRAD_STATUS  VARCHAR2(20),
  CONSTRAINT PK_RESUME_EDUCATION PRIMARY KEY (EDU_ID),
  CONSTRAINT FK_RESUME_EDU_EMP FOREIGN KEY (EMP_ID) REFERENCES RESUME_EMPLOYEE (EMP_ID)
);

-- 3. 자격증
CREATE TABLE RESUME_CERTIFICATION (
  CERT_ID    NUMBER GENERATED ALWAYS AS IDENTITY,
  EMP_ID     NUMBER        NOT NULL,
  CERT_NAME  VARCHAR2(100) NOT NULL,
  ACQ_DATE   DATE,
  CONSTRAINT PK_RESUME_CERTIFICATION PRIMARY KEY (CERT_ID),
  CONSTRAINT FK_RESUME_CERT_EMP FOREIGN KEY (EMP_ID) REFERENCES RESUME_EMPLOYEE (EMP_ID)
);

-- 4. 경력사항 (END_DATE NULL = 재직중)
CREATE TABLE RESUME_CAREER (
  CAREER_ID      NUMBER GENERATED ALWAYS AS IDENTITY,
  EMP_ID         NUMBER        NOT NULL,
  COMPANY_NAME   VARCHAR2(100) NOT NULL,
  START_DATE     DATE          NOT NULL,
  END_DATE       DATE,
  POSITION_TITLE VARCHAR2(50),
  JOB_DESC       VARCHAR2(500),
  CONSTRAINT PK_RESUME_CAREER PRIMARY KEY (CAREER_ID),
  CONSTRAINT FK_RESUME_CAREER_EMP FOREIGN KEY (EMP_ID) REFERENCES RESUME_EMPLOYEE (EMP_ID),
  CONSTRAINT CK_RESUME_CAREER_DATE CHECK (END_DATE IS NULL OR END_DATE >= START_DATE)
);

-- 5. 교육이력
CREATE TABLE RESUME_TRAINING (
  TRAIN_ID    NUMBER GENERATED ALWAYS AS IDENTITY,
  EMP_ID      NUMBER        NOT NULL,
  TRAIN_NAME  VARCHAR2(200) NOT NULL,
  START_DATE  DATE,
  END_DATE    DATE,
  INSTITUTION VARCHAR2(100),
  CONSTRAINT PK_RESUME_TRAINING PRIMARY KEY (TRAIN_ID),
  CONSTRAINT FK_RESUME_TRAIN_EMP FOREIGN KEY (EMP_ID) REFERENCES RESUME_EMPLOYEE (EMP_ID)
);

-- 6. 보유기술 및 외국어능력
CREATE TABLE RESUME_SKILL (
  SKILL_ID    NUMBER GENERATED ALWAYS AS IDENTITY,
  EMP_ID      NUMBER        NOT NULL,
  SKILL_NAME  VARCHAR2(100) NOT NULL,
  PROFICIENCY CHAR(1),
  CONSTRAINT PK_RESUME_SKILL PRIMARY KEY (SKILL_ID),
  CONSTRAINT FK_RESUME_SKILL_EMP FOREIGN KEY (EMP_ID) REFERENCES RESUME_EMPLOYEE (EMP_ID),
  CONSTRAINT UK_RESUME_SKILL UNIQUE (EMP_ID, SKILL_NAME),
  CONSTRAINT CK_RESUME_SKILL_PROF CHECK (PROFICIENCY IN ('A','B','C'))
);

-- 7. 프로젝트 수행이력 (SKILL INVENTORY)
CREATE TABLE RESUME_PROJECT (
  PROJECT_ID    NUMBER GENERATED ALWAYS AS IDENTITY,
  EMP_ID        NUMBER         NOT NULL,
  PROJECT_NAME  VARCHAR2(200)  NOT NULL,
  START_DATE    DATE,
  END_DATE      DATE,
  CLIENT_NAME   VARCHAR2(100),
  WORK_COMPANY  VARCHAR2(100),
  ROLE_NAME     VARCHAR2(50),
  ENV_MACHINE   VARCHAR2(100),
  ENV_OS        VARCHAR2(100),
  ENV_LANGUAGE  VARCHAR2(100),
  ENV_DBMS      VARCHAR2(100),
  ENV_TOOL      VARCHAR2(200),
  ENV_COMM      VARCHAR2(100),
  ENV_WAS       VARCHAR2(100),
  JOB_DESC      VARCHAR2(1000),
  CONSTRAINT PK_RESUME_PROJECT PRIMARY KEY (PROJECT_ID),
  CONSTRAINT FK_RESUME_PROJECT_EMP FOREIGN KEY (EMP_ID) REFERENCES RESUME_EMPLOYEE (EMP_ID),
  CONSTRAINT CK_RESUME_PROJECT_DATE CHECK (END_DATE IS NULL OR END_DATE >= START_DATE)
);

CREATE INDEX IX_RESUME_EDU_EMP     ON RESUME_EDUCATION (EMP_ID);
CREATE INDEX IX_RESUME_CERT_EMP    ON RESUME_CERTIFICATION (EMP_ID);
CREATE INDEX IX_RESUME_CAREER_EMP  ON RESUME_CAREER (EMP_ID);
CREATE INDEX IX_RESUME_TRAIN_EMP   ON RESUME_TRAINING (EMP_ID);
CREATE INDEX IX_RESUME_PROJECT_EMP ON RESUME_PROJECT (EMP_ID);

-- 코멘트
COMMENT ON TABLE  RESUME_EMPLOYEE      IS '인적사항(개인이력카드)';
COMMENT ON TABLE  RESUME_EDUCATION     IS '학력사항';
COMMENT ON TABLE  RESUME_CERTIFICATION IS '자격증';
COMMENT ON TABLE  RESUME_CAREER        IS '경력사항';
COMMENT ON TABLE  RESUME_TRAINING      IS '교육이력';
COMMENT ON TABLE  RESUME_SKILL         IS '보유기술 및 외국어능력';
COMMENT ON TABLE  RESUME_PROJECT       IS '프로젝트 수행이력(SKILL INVENTORY)';
COMMENT ON COLUMN RESUME_EMPLOYEE.GENDER          IS 'M:남, F:여';
COMMENT ON COLUMN RESUME_EMPLOYEE.MILITARY_STATUS IS '병적';
COMMENT ON COLUMN RESUME_EMPLOYEE.OTHER_SW        IS '기타(활용가능한 S/W 및 기법, FrameWork)';
COMMENT ON COLUMN RESUME_EDUCATION.GRAD_STATUS    IS '졸업/재학/휴학/중퇴 등';
COMMENT ON COLUMN RESUME_CAREER.END_DATE          IS 'NULL이면 재직중';
COMMENT ON COLUMN RESUME_SKILL.PROFICIENCY        IS '숙련도 A,B,C';
COMMENT ON COLUMN RESUME_PROJECT.ROLE_NAME        IS '역할';
COMMENT ON COLUMN RESUME_PROJECT.ENV_MACHINE      IS '개발환경-기종';
COMMENT ON COLUMN RESUME_PROJECT.ENV_COMM         IS '개발환경-통신';
COMMENT ON COLUMN RESUME_PROJECT.JOB_DESC         IS '수행업무';

-- ============================================================
-- 이력서.docx 데이터 적재
-- ============================================================
INSERT INTO RESUME_EMPLOYEE (EMP_NAME, ADDRESS, OTHER_SW)
VALUES ('홍길동', '경기도 화성시', 'CREO, AutoCAD, SolidWorks');
-- 생년월일은 원본이 'YYYY-MM-DD' 자리표시자라 NULL

INSERT INTO RESUME_EDUCATION (EMP_ID, SCHOOL_NAME, MAJOR, ENTER_DATE, GRAD_DATE, GRAD_STATUS)
VALUES (1, 'OOO고등학교', '인문계 이과', DATE '2008-03-03', DATE '2011-02-09', '졸업');
INSERT INTO RESUME_EDUCATION (EMP_ID, SCHOOL_NAME, MAJOR, ENTER_DATE, GRAD_DATE, GRAD_STATUS)
VALUES (1, 'OO대학교', 'XXX공학과', DATE '2011-03-02', DATE '2017-08-22', '졸업');

INSERT INTO RESUME_CAREER (EMP_ID, COMPANY_NAME, START_DATE, END_DATE, POSITION_TITLE, JOB_DESC)
VALUES (1, 'OOO', DATE '2019-04-01', DATE '2023-07-31', '대리', '기구설계 (CREO, AutoCAD)');
INSERT INTO RESUME_CAREER (EMP_ID, COMPANY_NAME, START_DATE, END_DATE, POSITION_TITLE, JOB_DESC)
VALUES (1, 'OOOOO', DATE '2023-08-03', DATE '2024-09-30', '선임', '기구설계 (CREO, AutoCAD)');
INSERT INTO RESUME_CAREER (EMP_ID, COMPANY_NAME, START_DATE, END_DATE, POSITION_TITLE, JOB_DESC)
VALUES (1, 'OOOOOO', DATE '2024-10-28', NULL, '선임', '공정물류 기구설계');

INSERT INTO RESUME_SKILL (EMP_ID, SKILL_NAME, PROFICIENCY) VALUES (1, 'AutoCAD', 'A');
INSERT INTO RESUME_SKILL (EMP_ID, SKILL_NAME, PROFICIENCY) VALUES (1, 'CREO', 'B');
INSERT INTO RESUME_SKILL (EMP_ID, SKILL_NAME, PROFICIENCY) VALUES (1, 'SolidWorks', 'B');

INSERT INTO RESUME_PROJECT (EMP_ID, PROJECT_NAME, START_DATE, END_DATE, CLIENT_NAME, WORK_COMPANY, ROLE_NAME, ENV_TOOL, JOB_DESC)
VALUES (1, 'LGD 파주공장 애플워치 셀자동화검사장비 구축 1단계', DATE '2019-09-01', DATE '2019-12-31', 'LGD', '소닉스', '설계', 'CREO, AutoCAD', 'CAMERA 파트 설계, 프레임 설계');
INSERT INTO RESUME_PROJECT (EMP_ID, PROJECT_NAME, START_DATE, END_DATE, CLIENT_NAME, WORK_COMPANY, ROLE_NAME, ENV_TOOL, JOB_DESC)
VALUES (1, 'LGD 파주공장 애플워치 셀자동화검사장비 구축 2단계', DATE '2020-09-01', DATE '2020-12-31', 'LGD', '소닉스', '설계', 'CREO, AutoCAD', 'CAMERA 파트 설계, 프레임 설계');
INSERT INTO RESUME_PROJECT (EMP_ID, PROJECT_NAME, START_DATE, END_DATE, CLIENT_NAME, WORK_COMPANY, ROLE_NAME, ENV_TOOL, JOB_DESC)
VALUES (1, 'LGD 파주공장 애플워치 셀 자동화 검사장비 구축 3단계', DATE '2021-09-01', DATE '2021-12-31', 'LGD', '소닉스', '설계', 'CREO, AutoCAD', 'CAMERA 파트 설계, 프레임 설계');

COMMIT;
