/*
    개인이력카드 (../이력서.docx) — Oracle DDL + seed

    대상: Oracle 12c 이상 (IDENTITY 컬럼)
    권장 문자셋: AL32UTF8. 길이는 VARCHAR2(n CHAR)로 문자 수 기준.
    재실행 가능: 자식 테이블을 먼저 DROP 한 뒤 부모를 DROP 한다.
    빈 칸, '-', 'YYYY-MM-DD' 자리표시는 NULL.
    '재직중'은 END_DATE NULL, IS_CURRENT = 1.
*/

SET DEFINE OFF;

/* ------------------------------------------------------------------ */
/* drop (children first)                                             */
/* ------------------------------------------------------------------ */

DECLARE
    TYPE name_list IS TABLE OF VARCHAR2(128);
    v_tables name_list := name_list(
        'RESUME_PROJECT',
        'RESUME_SKILL',
        'RESUME_TRAINING',
        'RESUME_CAREER',
        'RESUME_CERTIFICATE',
        'RESUME_EDUCATION',
        'RESUME'
    );
BEGIN
    FOR i IN 1 .. v_tables.COUNT LOOP
        BEGIN
            EXECUTE IMMEDIATE
                'DROP TABLE ' || v_tables(i) || ' CASCADE CONSTRAINTS PURGE';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -942 THEN
                    RAISE;
                END IF;
        END;
    END LOOP;
END;
/

/* ------------------------------------------------------------------ */
/* resume — 개인이력카드                                              */
/* ------------------------------------------------------------------ */

CREATE TABLE resume (
    resume_id         NUMBER         GENERATED BY DEFAULT AS IDENTITY,
    full_name         VARCHAR2(50 CHAR)   NOT NULL,          -- 성명
    birth_date        DATE,                                  -- 생년월일
    gender            VARCHAR2(10 CHAR),                     -- 성별
    company_name      VARCHAR2(100 CHAR),                    -- 소속회사
    hire_date         DATE,                                  -- 입사일자
    department        VARCHAR2(100 CHAR),                    -- 부서
    position          VARCHAR2(50 CHAR),                     -- 직위
    military_status   VARCHAR2(50 CHAR),                     -- 병적
    phone             VARCHAR2(30 CHAR),                     -- 전화
    email             VARCHAR2(200 CHAR),                    -- E-Mail
    address           VARCHAR2(300 CHAR),                    -- 주소
    other_skill_note  VARCHAR2(500 CHAR),                    -- 기타 (활용가능한 S/W 및 기법, FrameWork)
    CONSTRAINT pk_resume PRIMARY KEY (resume_id)
);

COMMENT ON TABLE resume IS '개인이력카드 기본 정보';
COMMENT ON COLUMN resume.full_name IS '성명';
COMMENT ON COLUMN resume.birth_date IS '생년월일';
COMMENT ON COLUMN resume.gender IS '성별';
COMMENT ON COLUMN resume.company_name IS '소속회사';
COMMENT ON COLUMN resume.hire_date IS '입사일자';
COMMENT ON COLUMN resume.department IS '부서';
COMMENT ON COLUMN resume.position IS '직위';
COMMENT ON COLUMN resume.military_status IS '병적';
COMMENT ON COLUMN resume.phone IS '전화';
COMMENT ON COLUMN resume.email IS 'E-Mail';
COMMENT ON COLUMN resume.address IS '주소';
COMMENT ON COLUMN resume.other_skill_note IS '기타 (활용가능한 S/W 및 기법, FrameWork)';

/* ------------------------------------------------------------------ */
/* resume_education — 학력사항                                        */
/* 양식 안내: 대학(교,원)의 입학일자도 표기                          */
/* ------------------------------------------------------------------ */

CREATE TABLE resume_education (
    education_id       NUMBER              GENERATED BY DEFAULT AS IDENTITY,
    resume_id          NUMBER              NOT NULL,
    school_name        VARCHAR2(100 CHAR)  NOT NULL,         -- 학교명
    major              VARCHAR2(100 CHAR),                   -- 전공/계열
    start_date         DATE,                                 -- 입학일
    end_date           DATE,                                 -- 졸업일
    graduation_status  VARCHAR2(20 CHAR),                    -- 졸업구분
    sort_order         NUMBER(5)           NOT NULL,         -- 문서 기재 순서
    CONSTRAINT pk_resume_education PRIMARY KEY (education_id),
    CONSTRAINT fk_resume_education_resume
        FOREIGN KEY (resume_id) REFERENCES resume (resume_id) ON DELETE CASCADE,
    CONSTRAINT ck_resume_education_dates
        CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_resume_education_sort
        CHECK (sort_order > 0)
);

CREATE INDEX ix_resume_education_resume_id
    ON resume_education (resume_id);

COMMENT ON TABLE resume_education IS '학력사항';
COMMENT ON COLUMN resume_education.school_name IS '학교명';
COMMENT ON COLUMN resume_education.major IS '전공/계열';
COMMENT ON COLUMN resume_education.start_date IS '입학일';
COMMENT ON COLUMN resume_education.end_date IS '졸업일';
COMMENT ON COLUMN resume_education.graduation_status IS '졸업구분';
COMMENT ON COLUMN resume_education.sort_order IS '문서 기재 순서';

/* ------------------------------------------------------------------ */
/* resume_certificate — 자격증명                                      */
/* 양식 열은 있으나 이 문서에는 데이터 행이 없다.                    */
/* ------------------------------------------------------------------ */

CREATE TABLE resume_certificate (
    certificate_id    NUMBER              GENERATED BY DEFAULT AS IDENTITY,
    resume_id         NUMBER              NOT NULL,
    certificate_name  VARCHAR2(200 CHAR)  NOT NULL,          -- 자격증명
    acquired_date     DATE,                                  -- 취득일
    sort_order        NUMBER(5)           NOT NULL,          -- 문서 기재 순서
    CONSTRAINT pk_resume_certificate PRIMARY KEY (certificate_id),
    CONSTRAINT fk_resume_certificate_resume
        FOREIGN KEY (resume_id) REFERENCES resume (resume_id) ON DELETE CASCADE,
    CONSTRAINT ck_resume_certificate_sort
        CHECK (sort_order > 0)
);

CREATE INDEX ix_resume_certificate_resume_id
    ON resume_certificate (resume_id);

COMMENT ON TABLE resume_certificate IS '자격증명';
COMMENT ON COLUMN resume_certificate.certificate_name IS '자격증명';
COMMENT ON COLUMN resume_certificate.acquired_date IS '취득일';
COMMENT ON COLUMN resume_certificate.sort_order IS '문서 기재 순서';

/* ------------------------------------------------------------------ */
/* resume_career — 경력                                               */
/* ------------------------------------------------------------------ */

CREATE TABLE resume_career (
    career_id     NUMBER              GENERATED BY DEFAULT AS IDENTITY,
    resume_id     NUMBER              NOT NULL,
    company_name  VARCHAR2(100 CHAR)  NOT NULL,              -- 회사명
    start_date    DATE,                                      -- 시작일
    end_date      DATE,                                      -- 종료일 (재직중이면 NULL)
    is_current    NUMBER(1)           DEFAULT 0 NOT NULL,    -- 재직중 (1/0)
    position      VARCHAR2(50 CHAR),                         -- 직위
    duties        VARCHAR2(500 CHAR),                        -- 담당업무
    sort_order    NUMBER(5)           NOT NULL,              -- 문서 기재 순서
    CONSTRAINT pk_resume_career PRIMARY KEY (career_id),
    CONSTRAINT fk_resume_career_resume
        FOREIGN KEY (resume_id) REFERENCES resume (resume_id) ON DELETE CASCADE,
    CONSTRAINT ck_resume_career_dates
        CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_resume_career_current
        CHECK (is_current IN (0, 1)),
    CONSTRAINT ck_resume_career_open_end
        CHECK (is_current = 0 OR end_date IS NULL),
    CONSTRAINT ck_resume_career_sort
        CHECK (sort_order > 0)
);

CREATE INDEX ix_resume_career_resume_id
    ON resume_career (resume_id);

COMMENT ON TABLE resume_career IS '경력';
COMMENT ON COLUMN resume_career.company_name IS '회사명';
COMMENT ON COLUMN resume_career.start_date IS '기간 시작일';
COMMENT ON COLUMN resume_career.end_date IS '기간 종료일. 재직중이면 NULL';
COMMENT ON COLUMN resume_career.is_current IS '재직중 여부 (1=재직중, 0=종료)';
COMMENT ON COLUMN resume_career.position IS '직위';
COMMENT ON COLUMN resume_career.duties IS '담당업무';
COMMENT ON COLUMN resume_career.sort_order IS '문서 기재 순서';

/* ------------------------------------------------------------------ */
/* resume_training — 교육                                             */
/* 양식 열은 있으나 이 문서에는 데이터 행이 없다.                    */
/* ------------------------------------------------------------------ */

CREATE TABLE resume_training (
    training_id    NUMBER              GENERATED BY DEFAULT AS IDENTITY,
    resume_id      NUMBER              NOT NULL,
    training_name  VARCHAR2(200 CHAR)  NOT NULL,             -- 교육명
    start_date     DATE,                                     -- 시작일
    end_date       DATE,                                     -- 종료일
    institution    VARCHAR2(200 CHAR),                       -- 기관
    sort_order     NUMBER(5)           NOT NULL,             -- 문서 기재 순서
    CONSTRAINT pk_resume_training PRIMARY KEY (training_id),
    CONSTRAINT fk_resume_training_resume
        FOREIGN KEY (resume_id) REFERENCES resume (resume_id) ON DELETE CASCADE,
    CONSTRAINT ck_resume_training_dates
        CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_resume_training_sort
        CHECK (sort_order > 0)
);

CREATE INDEX ix_resume_training_resume_id
    ON resume_training (resume_id);

COMMENT ON TABLE resume_training IS '교육';
COMMENT ON COLUMN resume_training.training_name IS '교육명';
COMMENT ON COLUMN resume_training.start_date IS '시작일';
COMMENT ON COLUMN resume_training.end_date IS '종료일';
COMMENT ON COLUMN resume_training.institution IS '기관';
COMMENT ON COLUMN resume_training.sort_order IS '문서 기재 순서';

/* ------------------------------------------------------------------ */
/* resume_skill — 보유기술 및 외국어능력                              */
/* ------------------------------------------------------------------ */

CREATE TABLE resume_skill (
    skill_id     NUMBER              GENERATED BY DEFAULT AS IDENTITY,
    resume_id    NUMBER              NOT NULL,
    skill_name   VARCHAR2(100 CHAR)  NOT NULL,               -- 보유기술 및 외국어
    proficiency  VARCHAR2(1 CHAR),                           -- 숙련도 (A, B, C)
    sort_order   NUMBER(5)           NOT NULL,               -- 문서 기재 순서
    CONSTRAINT pk_resume_skill PRIMARY KEY (skill_id),
    CONSTRAINT fk_resume_skill_resume
        FOREIGN KEY (resume_id) REFERENCES resume (resume_id) ON DELETE CASCADE,
    CONSTRAINT ck_resume_skill_proficiency
        CHECK (proficiency IS NULL OR proficiency IN ('A', 'B', 'C')),
    CONSTRAINT ck_resume_skill_sort
        CHECK (sort_order > 0)
);

CREATE INDEX ix_resume_skill_resume_id
    ON resume_skill (resume_id);

COMMENT ON TABLE resume_skill IS '보유기술 및 외국어능력';
COMMENT ON COLUMN resume_skill.skill_name IS '보유기술 및 외국어';
COMMENT ON COLUMN resume_skill.proficiency IS '숙련도 (A, B, C)';
COMMENT ON COLUMN resume_skill.sort_order IS '문서 기재 순서';

/* ------------------------------------------------------------------ */
/* resume_project — SKILL INVENTORY                                   */
/* 양식 안내: 가장 최근 프로젝트를 하단에 표기. sort_order가 그 순서. */
/* ------------------------------------------------------------------ */

CREATE TABLE resume_project (
    project_id        NUMBER               GENERATED BY DEFAULT AS IDENTITY,
    resume_id         NUMBER               NOT NULL,
    project_name      VARCHAR2(300 CHAR)   NOT NULL,         -- 프로젝트명 (시스템 명)
    start_date        DATE,                                  -- 참여 시작
    end_date          DATE,                                  -- 참여 종료
    customer_name     VARCHAR2(100 CHAR),                    -- 고객사
    employer_name     VARCHAR2(100 CHAR),                    -- 근무회사
    role_name         VARCHAR2(50 CHAR),                     -- 역할
    hw_model          VARCHAR2(100 CHAR),                    -- 개발환경 기종
    os_name           VARCHAR2(100 CHAR),                    -- 개발환경 OS
    language_name     VARCHAR2(100 CHAR),                    -- 개발환경 언어
    dbms_name         VARCHAR2(100 CHAR),                    -- 개발환경 DBMS
    tool_name         VARCHAR2(200 CHAR),                    -- 개발환경 TOOL
    communication     VARCHAR2(100 CHAR),                    -- 개발환경 통신
    was_name          VARCHAR2(100 CHAR),                    -- 개발환경 WAS
    work_description  VARCHAR2(1000 CHAR),                   -- 수행업무
    sort_order        NUMBER(5)            NOT NULL,         -- 문서 기재 순서
    CONSTRAINT pk_resume_project PRIMARY KEY (project_id),
    CONSTRAINT fk_resume_project_resume
        FOREIGN KEY (resume_id) REFERENCES resume (resume_id) ON DELETE CASCADE,
    CONSTRAINT ck_resume_project_dates
        CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_resume_project_sort
        CHECK (sort_order > 0)
);

CREATE INDEX ix_resume_project_resume_id
    ON resume_project (resume_id);

COMMENT ON TABLE resume_project IS 'SKILL INVENTORY 프로젝트';
COMMENT ON COLUMN resume_project.project_name IS '프로젝트명 (시스템 명)';
COMMENT ON COLUMN resume_project.start_date IS '참여기간 시작';
COMMENT ON COLUMN resume_project.end_date IS '참여기간 종료';
COMMENT ON COLUMN resume_project.customer_name IS '고객사';
COMMENT ON COLUMN resume_project.employer_name IS '근무회사';
COMMENT ON COLUMN resume_project.role_name IS '역할';
COMMENT ON COLUMN resume_project.hw_model IS '개발환경 기종';
COMMENT ON COLUMN resume_project.os_name IS '개발환경 OS';
COMMENT ON COLUMN resume_project.language_name IS '개발환경 언어';
COMMENT ON COLUMN resume_project.dbms_name IS '개발환경 DBMS';
COMMENT ON COLUMN resume_project.tool_name IS '개발환경 TOOL';
COMMENT ON COLUMN resume_project.communication IS '개발환경 통신';
COMMENT ON COLUMN resume_project.was_name IS '개발환경 WAS';
COMMENT ON COLUMN resume_project.work_description IS '수행업무';
COMMENT ON COLUMN resume_project.sort_order IS '문서 기재 순서 (최근 건이 아래)';

/* ------------------------------------------------------------------ */
/* seed: 이력서.docx (홍길동)                                         */
/* 자격증, 교육 행은 문서에 없어 INSERT 하지 않는다.                 */
/* ------------------------------------------------------------------ */

DECLARE
    v_resume_id NUMBER;
BEGIN
    INSERT INTO resume (
        full_name,
        birth_date,
        gender,
        company_name,
        hire_date,
        department,
        position,
        military_status,
        phone,
        email,
        address,
        other_skill_note
    ) VALUES (
        '홍길동',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '경기도 화성시',
        'CREO, AutoCAD, SolidWorks'
    )
    RETURNING resume_id INTO v_resume_id;

    INSERT INTO resume_education (
        resume_id, school_name, major, start_date, end_date, graduation_status, sort_order
    ) VALUES (
        v_resume_id, 'OOO고등학교', '인문계 이과',
        DATE '2008-03-03', DATE '2011-02-09', '졸업', 1
    );

    INSERT INTO resume_education (
        resume_id, school_name, major, start_date, end_date, graduation_status, sort_order
    ) VALUES (
        v_resume_id, 'OO대학교', 'XXX공학과',
        DATE '2011-03-02', DATE '2017-08-22', '졸업', 2
    );

    INSERT INTO resume_career (
        resume_id, company_name, start_date, end_date, is_current, position, duties, sort_order
    ) VALUES (
        v_resume_id, 'OOO',
        DATE '2019-04-01', DATE '2023-07-31', 0,
        '대리', '기구설계 (CREO, AutoCAD)', 1
    );

    INSERT INTO resume_career (
        resume_id, company_name, start_date, end_date, is_current, position, duties, sort_order
    ) VALUES (
        v_resume_id, 'OOOOO',
        DATE '2023-08-03', DATE '2024-09-30', 0,
        '선임', '기구설계 (CREO, AutoCAD)', 2
    );

    INSERT INTO resume_career (
        resume_id, company_name, start_date, end_date, is_current, position, duties, sort_order
    ) VALUES (
        v_resume_id, 'OOOOOO',
        DATE '2024-10-28', NULL, 1,
        '선임', '공정물류 기구설계', 3
    );

    INSERT INTO resume_skill (
        resume_id, skill_name, proficiency, sort_order
    ) VALUES (v_resume_id, 'AutoCAD', 'A', 1);

    INSERT INTO resume_skill (
        resume_id, skill_name, proficiency, sort_order
    ) VALUES (v_resume_id, 'CREO', 'B', 2);

    INSERT INTO resume_skill (
        resume_id, skill_name, proficiency, sort_order
    ) VALUES (v_resume_id, 'SolidWorks', 'B', 3);

    INSERT INTO resume_project (
        resume_id, project_name, start_date, end_date,
        customer_name, employer_name, role_name,
        hw_model, os_name, language_name, dbms_name, tool_name, communication, was_name,
        work_description, sort_order
    ) VALUES (
        v_resume_id,
        'LGD 파주공장 애플워치 셀자동화검사장비 구축 1단계',
        DATE '2019-09-01', DATE '2019-12-31',
        'LGD', '소닉스', '설계',
        NULL, NULL, NULL, NULL, 'CREO, AutoCAD', NULL, NULL,
        'CAMERA 파트 설계, 프레임 설계',
        1
    );

    INSERT INTO resume_project (
        resume_id, project_name, start_date, end_date,
        customer_name, employer_name, role_name,
        hw_model, os_name, language_name, dbms_name, tool_name, communication, was_name,
        work_description, sort_order
    ) VALUES (
        v_resume_id,
        'LGD 파주공장 애플워치 셀자동화검사장비 구축 2단계',
        DATE '2020-09-01', DATE '2020-12-31',
        'LGD', '소닉스', '설계',
        NULL, NULL, NULL, NULL, 'CREO, AutoCAD', NULL, NULL,
        'CAMERA 파트 설계, 프레임 설계',
        2
    );

    INSERT INTO resume_project (
        resume_id, project_name, start_date, end_date,
        customer_name, employer_name, role_name,
        hw_model, os_name, language_name, dbms_name, tool_name, communication, was_name,
        work_description, sort_order
    ) VALUES (
        v_resume_id,
        'LGD 파주공장 애플워치 셀 자동화 검사장비 구축 3단계',
        DATE '2021-09-01', DATE '2021-12-31',
        'LGD', '소닉스', '설계',
        NULL, NULL, NULL, NULL, 'CREO, AutoCAD', NULL, NULL,
        'CAMERA 파트 설계, 프레임 설계',
        3
    );

    COMMIT;
END;
/
