-- Oracle 19c 기준 (IDENTITY 사용: Oracle 12c 이상)
-- 기존 사용자 스키마에 실행. 재실행/기존 객체 삭제를 수행하지 않음.
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

CREATE TABLE RESUME_PROFILE (
    RESUME_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FULL_NAME VARCHAR2(100 CHAR) NOT NULL,
    BIRTH_DATE DATE,
    GENDER VARCHAR2(30 CHAR),
    COMPANY_NAME VARCHAR2(200 CHAR),
    JOIN_DATE DATE,
    DEPARTMENT_NAME VARCHAR2(200 CHAR),
    POSITION_NAME VARCHAR2(100 CHAR),
    MILITARY_STATUS VARCHAR2(100 CHAR),
    PHONE VARCHAR2(50 CHAR),
    EMAIL VARCHAR2(254 CHAR),
    ADDRESS VARCHAR2(500 CHAR),
    OTHER_SKILLS CLOB,
    AUTHOR_NAME VARCHAR2(100 CHAR),
    SOURCE_FILE VARCHAR2(255 CHAR),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RESUME_PROFILE PRIMARY KEY (RESUME_ID)
);

CREATE TABLE RESUME_EDUCATION (
    EDUCATION_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    RESUME_ID NUMBER NOT NULL,
    DISPLAY_ORDER NUMBER(4) NOT NULL,
    SCHOOL_NAME VARCHAR2(200 CHAR) NOT NULL,
    MAJOR_NAME VARCHAR2(200 CHAR),
    START_DATE DATE,
    END_DATE DATE,
    GRADUATION_STATUS VARCHAR2(50 CHAR),
    CONSTRAINT PK_RESUME_EDUCATION PRIMARY KEY (EDUCATION_ID),
    CONSTRAINT FK_EDUCATION_PROFILE FOREIGN KEY (RESUME_ID) REFERENCES RESUME_PROFILE (RESUME_ID),
    CONSTRAINT UK_EDUCATION_ORDER UNIQUE (RESUME_ID, DISPLAY_ORDER),
    CONSTRAINT CK_EDUCATION_ORDER CHECK (DISPLAY_ORDER > 0),
    CONSTRAINT CK_EDUCATION_DATES CHECK (END_DATE >= START_DATE)
);

CREATE TABLE RESUME_CERTIFICATE (
    CERTIFICATE_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    RESUME_ID NUMBER NOT NULL,
    DISPLAY_ORDER NUMBER(4) NOT NULL,
    CERTIFICATE_NAME VARCHAR2(200 CHAR) NOT NULL,
    ACQUIRED_DATE DATE,
    CONSTRAINT PK_RESUME_CERTIFICATE PRIMARY KEY (CERTIFICATE_ID),
    CONSTRAINT FK_CERTIFICATE_PROFILE FOREIGN KEY (RESUME_ID) REFERENCES RESUME_PROFILE (RESUME_ID),
    CONSTRAINT UK_CERTIFICATE_ORDER UNIQUE (RESUME_ID, DISPLAY_ORDER),
    CONSTRAINT CK_CERTIFICATE_ORDER CHECK (DISPLAY_ORDER > 0)
);

CREATE TABLE RESUME_CAREER (
    CAREER_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    RESUME_ID NUMBER NOT NULL,
    DISPLAY_ORDER NUMBER(4) NOT NULL,
    COMPANY_NAME VARCHAR2(200 CHAR) NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    IS_CURRENT CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    POSITION_NAME VARCHAR2(100 CHAR),
    DUTIES CLOB,
    CONSTRAINT PK_RESUME_CAREER PRIMARY KEY (CAREER_ID),
    CONSTRAINT FK_CAREER_PROFILE FOREIGN KEY (RESUME_ID) REFERENCES RESUME_PROFILE (RESUME_ID),
    CONSTRAINT UK_CAREER_ORDER UNIQUE (RESUME_ID, DISPLAY_ORDER),
    CONSTRAINT CK_CAREER_ORDER CHECK (DISPLAY_ORDER > 0),
    CONSTRAINT CK_CAREER_DATES CHECK (END_DATE >= START_DATE),
    CONSTRAINT CK_CAREER_CURRENT CHECK (IS_CURRENT IN ('Y', 'N')),
    CONSTRAINT CK_CAREER_END CHECK (IS_CURRENT = 'N' OR END_DATE IS NULL)
);

CREATE TABLE RESUME_TRAINING (
    TRAINING_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    RESUME_ID NUMBER NOT NULL,
    DISPLAY_ORDER NUMBER(4) NOT NULL,
    TRAINING_NAME VARCHAR2(300 CHAR) NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    INSTITUTION_NAME VARCHAR2(200 CHAR),
    CONSTRAINT PK_RESUME_TRAINING PRIMARY KEY (TRAINING_ID),
    CONSTRAINT FK_TRAINING_PROFILE FOREIGN KEY (RESUME_ID) REFERENCES RESUME_PROFILE (RESUME_ID),
    CONSTRAINT UK_TRAINING_ORDER UNIQUE (RESUME_ID, DISPLAY_ORDER),
    CONSTRAINT CK_TRAINING_ORDER CHECK (DISPLAY_ORDER > 0),
    CONSTRAINT CK_TRAINING_DATES CHECK (END_DATE >= START_DATE)
);

CREATE TABLE RESUME_SKILL (
    SKILL_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    RESUME_ID NUMBER NOT NULL,
    DISPLAY_ORDER NUMBER(4) NOT NULL,
    SKILL_NAME VARCHAR2(200 CHAR) NOT NULL,
    PROFICIENCY CHAR(1 CHAR),
    CONSTRAINT PK_RESUME_SKILL PRIMARY KEY (SKILL_ID),
    CONSTRAINT FK_SKILL_PROFILE FOREIGN KEY (RESUME_ID) REFERENCES RESUME_PROFILE (RESUME_ID),
    CONSTRAINT UK_SKILL_ORDER UNIQUE (RESUME_ID, DISPLAY_ORDER),
    CONSTRAINT CK_SKILL_ORDER CHECK (DISPLAY_ORDER > 0),
    CONSTRAINT CK_SKILL_PROFICIENCY CHECK (PROFICIENCY IN ('A', 'B', 'C'))
);

CREATE TABLE RESUME_PROJECT (
    PROJECT_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    RESUME_ID NUMBER NOT NULL,
    DISPLAY_ORDER NUMBER(4) NOT NULL,
    PROJECT_NAME VARCHAR2(500 CHAR) NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    CUSTOMER_NAME VARCHAR2(200 CHAR),
    WORK_COMPANY_NAME VARCHAR2(200 CHAR),
    ROLE_NAME VARCHAR2(100 CHAR),
    DUTIES CLOB,
    CONSTRAINT PK_RESUME_PROJECT PRIMARY KEY (PROJECT_ID),
    CONSTRAINT FK_PROJECT_PROFILE FOREIGN KEY (RESUME_ID) REFERENCES RESUME_PROFILE (RESUME_ID),
    CONSTRAINT UK_PROJECT_ORDER UNIQUE (RESUME_ID, DISPLAY_ORDER),
    CONSTRAINT CK_PROJECT_ORDER CHECK (DISPLAY_ORDER > 0),
    CONSTRAINT CK_PROJECT_DATES CHECK (END_DATE >= START_DATE)
);

CREATE TABLE RESUME_PROJECT_ENV (
    PROJECT_ENV_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PROJECT_ID NUMBER NOT NULL,
    ENV_TYPE VARCHAR2(20 CHAR) NOT NULL,
    DISPLAY_ORDER NUMBER(4) NOT NULL,
    ENV_VALUE VARCHAR2(300 CHAR) NOT NULL,
    CONSTRAINT PK_RESUME_PROJECT_ENV PRIMARY KEY (PROJECT_ENV_ID),
    CONSTRAINT FK_PROJECT_ENV_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES RESUME_PROJECT (PROJECT_ID),
    CONSTRAINT UK_PROJECT_ENV_ORDER UNIQUE (PROJECT_ID, ENV_TYPE, DISPLAY_ORDER),
    CONSTRAINT CK_PROJECT_ENV_ORDER CHECK (DISPLAY_ORDER > 0),
    CONSTRAINT CK_PROJECT_ENV_TYPE CHECK (ENV_TYPE IN ('MACHINE', 'OS', 'LANGUAGE', 'DBMS', 'TOOL', 'COMMUNICATION', 'WAS'))
);

-- UNIQUE 인덱스의 선두 열이 FK이므로 별도의 중복 FK 인덱스는 생성하지 않음.
COMMENT ON TABLE RESUME_PROFILE IS '개인 이력 카드 기본정보 및 원문 기타 기술';
COMMENT ON TABLE RESUME_EDUCATION IS '학력사항';
COMMENT ON TABLE RESUME_CERTIFICATE IS '자격증 취득 이력';
COMMENT ON TABLE RESUME_CAREER IS '회사별 경력사항';
COMMENT ON TABLE RESUME_TRAINING IS '교육 이력';
COMMENT ON TABLE RESUME_SKILL IS '보유기술 및 외국어능력';
COMMENT ON TABLE RESUME_PROJECT IS 'SKILL INVENTORY 프로젝트 참여 이력';
COMMENT ON TABLE RESUME_PROJECT_ENV IS '프로젝트별 개발환경 항목과 개별 값';

COMMENT ON COLUMN RESUME_PROFILE.RESUME_ID IS '이력서 식별자 자동 생성';
COMMENT ON COLUMN RESUME_PROFILE.FULL_NAME IS '성명';
COMMENT ON COLUMN RESUME_PROFILE.BIRTH_DATE IS '생년월일 미기재 및 자리표시는 NULL';
COMMENT ON COLUMN RESUME_PROFILE.GENDER IS '성별 원문';
COMMENT ON COLUMN RESUME_PROFILE.COMPANY_NAME IS '기본정보 소속회사 원문';
COMMENT ON COLUMN RESUME_PROFILE.JOIN_DATE IS '기본정보 입사일자';
COMMENT ON COLUMN RESUME_PROFILE.DEPARTMENT_NAME IS '부서';
COMMENT ON COLUMN RESUME_PROFILE.POSITION_NAME IS '기본정보 직위';
COMMENT ON COLUMN RESUME_PROFILE.MILITARY_STATUS IS '병적 원문';
COMMENT ON COLUMN RESUME_PROFILE.PHONE IS '전화번호';
COMMENT ON COLUMN RESUME_PROFILE.EMAIL IS '이메일';
COMMENT ON COLUMN RESUME_PROFILE.ADDRESS IS '주소';
COMMENT ON COLUMN RESUME_PROFILE.OTHER_SKILLS IS '기타 활용가능한 S/W 및 기법 FrameWork 원문';
COMMENT ON COLUMN RESUME_PROFILE.AUTHOR_NAME IS '작성자 미기재 시 NULL';
COMMENT ON COLUMN RESUME_PROFILE.SOURCE_FILE IS '입력 문서 파일명';
COMMENT ON COLUMN RESUME_PROFILE.CREATED_AT IS 'DB 적재 시각 문서 작성일 아님';
COMMENT ON COLUMN RESUME_EDUCATION.SCHOOL_NAME IS '학교명';
COMMENT ON COLUMN RESUME_EDUCATION.MAJOR_NAME IS '계열 또는 전공';
COMMENT ON COLUMN RESUME_EDUCATION.START_DATE IS '입학일';
COMMENT ON COLUMN RESUME_EDUCATION.END_DATE IS '졸업 또는 종료일';
COMMENT ON COLUMN RESUME_EDUCATION.GRADUATION_STATUS IS '졸업 상태 원문';
COMMENT ON COLUMN RESUME_CERTIFICATE.CERTIFICATE_NAME IS '자격증명';
COMMENT ON COLUMN RESUME_CERTIFICATE.ACQUIRED_DATE IS '취득일';
COMMENT ON COLUMN RESUME_CAREER.COMPANY_NAME IS '경력 회사명 원문 익명 표기 유지';
COMMENT ON COLUMN RESUME_CAREER.START_DATE IS '경력 시작일';
COMMENT ON COLUMN RESUME_CAREER.END_DATE IS '경력 종료일 재직중은 NULL';
COMMENT ON COLUMN RESUME_CAREER.IS_CURRENT IS '문서 기준 재직중 여부 Y/N 현재 시점 사실을 보증하지 않음';
COMMENT ON COLUMN RESUME_CAREER.POSITION_NAME IS '경력 직위';
COMMENT ON COLUMN RESUME_CAREER.DUTIES IS '담당 업무 원문';
COMMENT ON COLUMN RESUME_TRAINING.TRAINING_NAME IS '교육명';
COMMENT ON COLUMN RESUME_TRAINING.START_DATE IS '교육 시작일';
COMMENT ON COLUMN RESUME_TRAINING.END_DATE IS '교육 종료일';
COMMENT ON COLUMN RESUME_TRAINING.INSTITUTION_NAME IS '교육 기관';
COMMENT ON COLUMN RESUME_SKILL.SKILL_NAME IS '기술 또는 외국어명';
COMMENT ON COLUMN RESUME_SKILL.PROFICIENCY IS '숙련도 A/B/C 원문 등급 의미는 미정의';
COMMENT ON COLUMN RESUME_PROJECT.PROJECT_NAME IS '프로젝트명 또는 시스템명 원문';
COMMENT ON COLUMN RESUME_PROJECT.START_DATE IS '참여 시작일 실제 입력된 일자 보존';
COMMENT ON COLUMN RESUME_PROJECT.END_DATE IS '참여 종료일 실제 입력된 일자 보존';
COMMENT ON COLUMN RESUME_PROJECT.CUSTOMER_NAME IS '고객사';
COMMENT ON COLUMN RESUME_PROJECT.WORK_COMPANY_NAME IS '근무회사 경력 회사와 임의 매핑하지 않음';
COMMENT ON COLUMN RESUME_PROJECT.ROLE_NAME IS '프로젝트 역할';
COMMENT ON COLUMN RESUME_PROJECT.DUTIES IS '수행업무 원문';
COMMENT ON COLUMN RESUME_PROJECT_ENV.ENV_TYPE IS 'MACHINE 기종 OS 운영체제 LANGUAGE 언어 DBMS 데이터베이스 TOOL 도구 COMMUNICATION 통신 WAS';
COMMENT ON COLUMN RESUME_PROJECT_ENV.ENV_VALUE IS '개발환경 개별 값 복수 도구는 행 분리';
