-- schema_oracle.sql 실행 후 최초 1회 실행. 재실행하면 별도 이력서로 중복 적재됨.
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
    v_resume_id RESUME_PROFILE.RESUME_ID%TYPE;
    v_project_id RESUME_PROJECT.PROJECT_ID%TYPE;
BEGIN
    INSERT INTO RESUME_PROFILE (FULL_NAME, ADDRESS, OTHER_SKILLS, SOURCE_FILE)
    VALUES ('홍길동', '경기도 화성시', 'CREO, AutoCAD, SolidWorks', '이력서.docx')
    RETURNING RESUME_ID INTO v_resume_id;

    INSERT INTO RESUME_EDUCATION (RESUME_ID, DISPLAY_ORDER, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, GRADUATION_STATUS)
    VALUES (v_resume_id, 1, 'OOO고등학교', '인문계 이과', DATE '2008-03-03', DATE '2011-02-09', '졸업');
    INSERT INTO RESUME_EDUCATION (RESUME_ID, DISPLAY_ORDER, SCHOOL_NAME, MAJOR_NAME, START_DATE, END_DATE, GRADUATION_STATUS)
    VALUES (v_resume_id, 2, 'OO대학교', 'XXX공학과', DATE '2011-03-02', DATE '2017-08-22', '졸업');

    INSERT INTO RESUME_CAREER (RESUME_ID, DISPLAY_ORDER, COMPANY_NAME, START_DATE, END_DATE, IS_CURRENT, POSITION_NAME, DUTIES)
    VALUES (v_resume_id, 1, 'OOO', DATE '2019-04-01', DATE '2023-07-31', 'N', '대리', '기구설계 (CREO, AutoCAD)');
    INSERT INTO RESUME_CAREER (RESUME_ID, DISPLAY_ORDER, COMPANY_NAME, START_DATE, END_DATE, IS_CURRENT, POSITION_NAME, DUTIES)
    VALUES (v_resume_id, 2, 'OOOOO', DATE '2023-08-03', DATE '2024-09-30', 'N', '선임', '기구설계 (CREO, AutoCAD)');
    INSERT INTO RESUME_CAREER (RESUME_ID, DISPLAY_ORDER, COMPANY_NAME, START_DATE, END_DATE, IS_CURRENT, POSITION_NAME, DUTIES)
    VALUES (v_resume_id, 3, 'OOOOOO', DATE '2024-10-28', NULL, 'Y', '선임', '공정물류 기구설계');

    INSERT INTO RESUME_SKILL (RESUME_ID, DISPLAY_ORDER, SKILL_NAME, PROFICIENCY)
    VALUES (v_resume_id, 1, 'AutoCAD', 'A');
    INSERT INTO RESUME_SKILL (RESUME_ID, DISPLAY_ORDER, SKILL_NAME, PROFICIENCY)
    VALUES (v_resume_id, 2, 'CREO', 'B');
    INSERT INTO RESUME_SKILL (RESUME_ID, DISPLAY_ORDER, SKILL_NAME, PROFICIENCY)
    VALUES (v_resume_id, 3, 'SolidWorks', 'B');

    INSERT INTO RESUME_PROJECT (RESUME_ID, DISPLAY_ORDER, PROJECT_NAME, START_DATE, END_DATE, CUSTOMER_NAME, WORK_COMPANY_NAME, ROLE_NAME, DUTIES)
    VALUES (v_resume_id, 1, 'LGD 파주공장 애플워치 셀자동화검사장비 구축 1단계', DATE '2019-09-01', DATE '2019-12-31', 'LGD', '소닉스', '설계', 'CAMERA 파트 설계, 프레임 설계')
    RETURNING PROJECT_ID INTO v_project_id;
    INSERT INTO RESUME_PROJECT_ENV (PROJECT_ID, ENV_TYPE, DISPLAY_ORDER, ENV_VALUE) VALUES (v_project_id, 'TOOL', 1, 'CREO');
    INSERT INTO RESUME_PROJECT_ENV (PROJECT_ID, ENV_TYPE, DISPLAY_ORDER, ENV_VALUE) VALUES (v_project_id, 'TOOL', 2, 'AutoCAD');

    INSERT INTO RESUME_PROJECT (RESUME_ID, DISPLAY_ORDER, PROJECT_NAME, START_DATE, END_DATE, CUSTOMER_NAME, WORK_COMPANY_NAME, ROLE_NAME, DUTIES)
    VALUES (v_resume_id, 2, 'LGD 파주공장 애플워치 셀자동화검사장비 구축 2단계', DATE '2020-09-01', DATE '2020-12-31', 'LGD', '소닉스', '설계', 'CAMERA 파트 설계, 프레임 설계')
    RETURNING PROJECT_ID INTO v_project_id;
    INSERT INTO RESUME_PROJECT_ENV (PROJECT_ID, ENV_TYPE, DISPLAY_ORDER, ENV_VALUE) VALUES (v_project_id, 'TOOL', 1, 'CREO');
    INSERT INTO RESUME_PROJECT_ENV (PROJECT_ID, ENV_TYPE, DISPLAY_ORDER, ENV_VALUE) VALUES (v_project_id, 'TOOL', 2, 'AutoCAD');

    INSERT INTO RESUME_PROJECT (RESUME_ID, DISPLAY_ORDER, PROJECT_NAME, START_DATE, END_DATE, CUSTOMER_NAME, WORK_COMPANY_NAME, ROLE_NAME, DUTIES)
    VALUES (v_resume_id, 3, 'LGD 파주공장 애플워치 셀 자동화 검사장비 구축 3단계', DATE '2021-09-01', DATE '2021-12-31', 'LGD', '소닉스', '설계', 'CAMERA 파트 설계, 프레임 설계')
    RETURNING PROJECT_ID INTO v_project_id;
    INSERT INTO RESUME_PROJECT_ENV (PROJECT_ID, ENV_TYPE, DISPLAY_ORDER, ENV_VALUE) VALUES (v_project_id, 'TOOL', 1, 'CREO');
    INSERT INTO RESUME_PROJECT_ENV (PROJECT_ID, ENV_TYPE, DISPLAY_ORDER, ENV_VALUE) VALUES (v_project_id, 'TOOL', 2, 'AutoCAD');

    -- 자격증과 교육은 원문에 실제 레코드가 없어 INSERT하지 않음.
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
