-- 빈 스키마에 DDL 및 seed를 각각 1회 실행한 후 기대 건수 비교.
SELECT TABLE_NAME, EXPECTED_COUNT, ACTUAL_COUNT,
       CASE WHEN EXPECTED_COUNT = ACTUAL_COUNT THEN 'PASS' ELSE 'CHECK' END AS RESULT
FROM (
    SELECT 'RESUME_PROFILE' TABLE_NAME, 1 EXPECTED_COUNT, COUNT(*) ACTUAL_COUNT FROM RESUME_PROFILE
    UNION ALL SELECT 'RESUME_EDUCATION', 2, COUNT(*) FROM RESUME_EDUCATION
    UNION ALL SELECT 'RESUME_CERTIFICATE', 0, COUNT(*) FROM RESUME_CERTIFICATE
    UNION ALL SELECT 'RESUME_CAREER', 3, COUNT(*) FROM RESUME_CAREER
    UNION ALL SELECT 'RESUME_TRAINING', 0, COUNT(*) FROM RESUME_TRAINING
    UNION ALL SELECT 'RESUME_SKILL', 3, COUNT(*) FROM RESUME_SKILL
    UNION ALL SELECT 'RESUME_PROJECT', 3, COUNT(*) FROM RESUME_PROJECT
    UNION ALL SELECT 'RESUME_PROJECT_ENV', 6, COUNT(*) FROM RESUME_PROJECT_ENV
)
ORDER BY TABLE_NAME;

-- 프로젝트별 도구 및 수행업무. 일자순 정렬하여 최근 프로젝트를 하단에 표시.
SELECT r.FULL_NAME, p.PROJECT_NAME,
       TO_CHAR(p.START_DATE, 'YYYY-MM-DD') START_DATE,
       TO_CHAR(p.END_DATE, 'YYYY-MM-DD') END_DATE,
       p.CUSTOMER_NAME, p.WORK_COMPANY_NAME, p.ROLE_NAME, e.TOOLS, p.DUTIES
FROM RESUME_PROFILE r
JOIN RESUME_PROJECT p ON p.RESUME_ID = r.RESUME_ID
LEFT JOIN (
    SELECT PROJECT_ID, LISTAGG(ENV_VALUE, ', ') WITHIN GROUP (ORDER BY DISPLAY_ORDER) TOOLS
    FROM RESUME_PROJECT_ENV
    WHERE ENV_TYPE = 'TOOL'
    GROUP BY PROJECT_ID
) e ON e.PROJECT_ID = p.PROJECT_ID
ORDER BY r.RESUME_ID, p.START_DATE NULLS LAST, p.DISPLAY_ORDER;
