-- Oracle Database 12c or later
-- Resume schema. Run this file once in the target schema.

CREATE TABLE resume_profile (
    resume_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    full_name          VARCHAR2(100 CHAR) NOT NULL,
    birth_date         DATE,
    gender             VARCHAR2(20 CHAR),
    affiliated_company VARCHAR2(200 CHAR),
    hire_date          DATE,
    department         VARCHAR2(200 CHAR),
    job_title          VARCHAR2(100 CHAR),
    military_status    VARCHAR2(100 CHAR),
    phone              VARCHAR2(50 CHAR),
    email              VARCHAR2(320 CHAR),
    address            VARCHAR2(500 CHAR),
    CONSTRAINT pk_resume_profile PRIMARY KEY (resume_id)
);

CREATE TABLE resume_education (
    education_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    resume_id          NUMBER NOT NULL,
    institution_name   VARCHAR2(200 CHAR) NOT NULL,
    major              VARCHAR2(200 CHAR),
    education_type     VARCHAR2(100 CHAR),
    start_date         DATE,
    end_date           DATE,
    completion_status  VARCHAR2(50 CHAR),
    CONSTRAINT pk_resume_education PRIMARY KEY (education_id),
    CONSTRAINT fk_education_resume FOREIGN KEY (resume_id)
        REFERENCES resume_profile (resume_id),
    CONSTRAINT ck_education_dates CHECK (
        end_date IS NULL OR start_date IS NULL OR end_date >= start_date
    )
);

CREATE TABLE resume_career (
    career_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    resume_id          NUMBER NOT NULL,
    company_name       VARCHAR2(200 CHAR) NOT NULL,
    start_date         DATE,
    end_date           DATE,
    is_current         CHAR(1) DEFAULT 'N' NOT NULL,
    job_title          VARCHAR2(100 CHAR),
    responsibilities   VARCHAR2(2000 CHAR),
    CONSTRAINT pk_resume_career PRIMARY KEY (career_id),
    CONSTRAINT fk_career_resume FOREIGN KEY (resume_id)
        REFERENCES resume_profile (resume_id),
    CONSTRAINT ck_career_dates CHECK (
        end_date IS NULL OR start_date IS NULL OR end_date >= start_date
    ),
    CONSTRAINT ck_career_current CHECK (
        (is_current = 'Y' AND end_date IS NULL)
        OR (is_current = 'N')
    ),
    CONSTRAINT ck_career_current_flag CHECK (is_current IN ('Y', 'N'))
);

CREATE TABLE resume_skill (
    skill_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    resume_id          NUMBER NOT NULL,
    skill_name         VARCHAR2(150 CHAR) NOT NULL,
    proficiency        CHAR(1),
    CONSTRAINT pk_resume_skill PRIMARY KEY (skill_id),
    CONSTRAINT fk_skill_resume FOREIGN KEY (resume_id)
        REFERENCES resume_profile (resume_id),
    CONSTRAINT ck_skill_proficiency CHECK (
        proficiency IS NULL OR proficiency IN ('A', 'B', 'C')
    ),
    CONSTRAINT uq_resume_skill UNIQUE (resume_id, skill_name)
);

CREATE TABLE resume_certificate (
    certificate_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    resume_id         NUMBER NOT NULL,
    certificate_name  VARCHAR2(200 CHAR) NOT NULL,
    acquired_date     DATE,
    CONSTRAINT pk_resume_certificate PRIMARY KEY (certificate_id),
    CONSTRAINT fk_certificate_resume FOREIGN KEY (resume_id)
        REFERENCES resume_profile (resume_id)
);

CREATE TABLE resume_training (
    training_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    resume_id         NUMBER NOT NULL,
    training_name     VARCHAR2(300 CHAR) NOT NULL,
    start_date        DATE,
    end_date          DATE,
    institution_name  VARCHAR2(200 CHAR),
    CONSTRAINT pk_resume_training PRIMARY KEY (training_id),
    CONSTRAINT fk_training_resume FOREIGN KEY (resume_id)
        REFERENCES resume_profile (resume_id),
    CONSTRAINT ck_training_dates CHECK (
        end_date IS NULL OR start_date IS NULL OR end_date >= start_date
    )
);

CREATE TABLE resume_project (
    project_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    resume_id         NUMBER NOT NULL,
    project_name      VARCHAR2(500 CHAR) NOT NULL,
    start_date        DATE,
    end_date          DATE,
    client_name       VARCHAR2(200 CHAR),
    company_name      VARCHAR2(200 CHAR),
    project_role      VARCHAR2(100 CHAR),
    platform          VARCHAR2(200 CHAR),
    operating_system  VARCHAR2(200 CHAR),
    programming_lang  VARCHAR2(200 CHAR),
    dbms              VARCHAR2(200 CHAR),
    communication     VARCHAR2(200 CHAR),
    application_server VARCHAR2(200 CHAR),
    responsibilities  VARCHAR2(2000 CHAR),
    CONSTRAINT pk_resume_project PRIMARY KEY (project_id),
    CONSTRAINT fk_project_resume FOREIGN KEY (resume_id)
        REFERENCES resume_profile (resume_id),
    CONSTRAINT ck_project_dates CHECK (
        end_date IS NULL OR start_date IS NULL OR end_date >= start_date
    )
);

CREATE TABLE resume_project_tool (
    project_id        NUMBER NOT NULL,
    tool_name         VARCHAR2(150 CHAR) NOT NULL,
    CONSTRAINT pk_resume_project_tool PRIMARY KEY (project_id, tool_name),
    CONSTRAINT fk_project_tool_project FOREIGN KEY (project_id)
        REFERENCES resume_project (project_id)
);

CREATE INDEX ix_education_resume ON resume_education (resume_id);
CREATE INDEX ix_career_resume ON resume_career (resume_id);
CREATE INDEX ix_project_resume ON resume_project (resume_id);

COMMENT ON TABLE resume_profile IS '이력서 기본 인적사항';
COMMENT ON TABLE resume_education IS '학력사항';
COMMENT ON TABLE resume_career IS '경력사항';
COMMENT ON TABLE resume_skill IS '보유 기술 및 숙련도';
COMMENT ON TABLE resume_certificate IS '자격증 취득사항';
COMMENT ON TABLE resume_training IS '교육 이수사항';
COMMENT ON TABLE resume_project IS '프로젝트 수행 이력 및 개발환경';
COMMENT ON TABLE resume_project_tool IS '프로젝트별 사용 도구';
