-- =====================================================================
-- 개인이력카드(이력서.docx) DB 스키마 + 데이터
-- DBMS : Oracle 12c 이상 (IDENTITY 컬럼 사용)
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. 재실행용 DROP (자식 테이블부터)
-- ---------------------------------------------------------------------
BEGIN
  FOR t IN (SELECT table_name FROM user_tables
             WHERE table_name IN ('RSM_PROJECT','RSM_SKILL','RSM_TRAINING',
                                  'RSM_CAREER','RSM_CERTIFICATE','RSM_EDUCATION','RSM_PERSON'))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

-- ---------------------------------------------------------------------
-- 1. 인적사항 (개인이력카드 상단 + 연락처 + 기타 + 작성자)
-- ---------------------------------------------------------------------
CREATE TABLE RSM_PERSON (
  PERSON_ID        NUMBER GENERATED ALWAYS AS IDENTITY,
  PERSON_NAME      VARCHAR2(50)   NOT NULL,
  BIRTH_DATE       DATE,
  GENDER           CHAR(1),
  COMPANY_NAME     VARCHAR2(100),
  HIRE_DATE        DATE,
  DEPT_NAME        VARCHAR2(100),
  POSITION_NAME    VARCHAR2(50),
  MILITARY_STATUS  VARCHAR2(50),
  PHONE            VARCHAR2(30),
  EMAIL            VARCHAR2(100),
  ADDRESS          VARCHAR2(300),
  ETC_SKILLS       VARCHAR2(1000),
  WRITER_NAME      VARCHAR2(50),
  CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_RSM_PERSON PRIMARY KEY (PERSON_ID),
  CONSTRAINT CK_RSM_PERSON_GENDER CHECK (GENDER IN ('M','F'))
);

COMMENT ON TABLE  RSM_PERSON                 IS '인적사항';
COMMENT ON COLUMN RSM_PERSON.PERSON_ID       IS '인원ID';
COMMENT ON COLUMN RSM_PERSON.PERSON_NAME     IS '성명';
COMMENT ON COLUMN RSM_PERSON.BIRTH_DATE      IS '생년월일';
COMMENT ON COLUMN RSM_PERSON.GENDER          IS '성별(M/F)';
COMMENT ON COLUMN RSM_PERSON.COMPANY_NAME    IS '소속회사';
COMMENT ON COLUMN RSM_PERSON.HIRE_DATE       IS '입사일자';
COMMENT ON COLUMN RSM_PERSON.DEPT_NAME       IS '부서';
COMMENT ON COLUMN RSM_PERSON.POSITION_NAME   IS '직위';
COMMENT ON COLUMN RSM_PERSON.MILITARY_STATUS IS '병적';
COMMENT ON COLUMN RSM_PERSON.PHONE           IS '전화';
COMMENT ON COLUMN RSM_PERSON.EMAIL           IS 'E-Mail';
COMMENT ON COLUMN RSM_PERSON.ADDRESS         IS '주소';
COMMENT ON COLUMN RSM_PERSON.ETC_SKILLS      IS '기타(활용가능한 S/W 및 기법, FrameWork)';
COMMENT ON COLUMN RSM_PERSON.WRITER_NAME     IS '작성자';
COMMENT ON COLUMN RSM_PERSON.CREATED_AT      IS '등록일시';

-- ---------------------------------------------------------------------
-- 2. 학력사항
-- ---------------------------------------------------------------------
CREATE TABLE RSM_EDUCATION (
  EDU_ID           NUMBER GENERATED ALWAYS AS IDENTITY,
  PERSON_ID        NUMBER         NOT NULL,
  SCHOOL_NAME      VARCHAR2(100)  NOT NULL,
  MAJOR_NAME       VARCHAR2(100),
  ADMISSION_DATE   DATE,
  GRADUATION_DATE  DATE,
  GRAD_STATUS      VARCHAR2(20),
  CONSTRAINT PK_RSM_EDUCATION PRIMARY KEY (EDU_ID),
  CONSTRAINT FK_RSM_EDUCATION_PERSON FOREIGN KEY (PERSON_ID) REFERENCES RSM_PERSON (PERSON_ID) ON DELETE CASCADE
);

COMMENT ON TABLE  RSM_EDUCATION                 IS '학력사항';
COMMENT ON COLUMN RSM_EDUCATION.EDU_ID          IS '학력ID';
COMMENT ON COLUMN RSM_EDUCATION.PERSON_ID       IS '인원ID';
COMMENT ON COLUMN RSM_EDUCATION.SCHOOL_NAME     IS '학교명';
COMMENT ON COLUMN RSM_EDUCATION.MAJOR_NAME      IS '전공(계열)';
COMMENT ON COLUMN RSM_EDUCATION.ADMISSION_DATE  IS '입학일자';
COMMENT ON COLUMN RSM_EDUCATION.GRADUATION_DATE IS '졸업일자';
COMMENT ON COLUMN RSM_EDUCATION.GRAD_STATUS     IS '졸업구분(졸업/수료/재학/중퇴 등)';

-- ---------------------------------------------------------------------
-- 3. 자격증
-- ---------------------------------------------------------------------
CREATE TABLE RSM_CERTIFICATE (
  CERT_ID          NUMBER GENERATED ALWAYS AS IDENTITY,
  PERSON_ID        NUMBER         NOT NULL,
  CERT_NAME        VARCHAR2(100)  NOT NULL,
  ACQUIRED_DATE    DATE,
  CONSTRAINT PK_RSM_CERTIFICATE PRIMARY KEY (CERT_ID),
  CONSTRAINT FK_RSM_CERTIFICATE_PERSON FOREIGN KEY (PERSON_ID) REFERENCES RSM_PERSON (PERSON_ID) ON DELETE CASCADE
);

COMMENT ON TABLE  RSM_CERTIFICATE               IS '자격증';
COMMENT ON COLUMN RSM_CERTIFICATE.CERT_ID       IS '자격증ID';
COMMENT ON COLUMN RSM_CERTIFICATE.PERSON_ID     IS '인원ID';
COMMENT ON COLUMN RSM_CERTIFICATE.CERT_NAME     IS '자격증명';
COMMENT ON COLUMN RSM_CERTIFICATE.ACQUIRED_DATE IS '취득일';

-- ---------------------------------------------------------------------
-- 4. 경력사항
-- ---------------------------------------------------------------------
CREATE TABLE RSM_CAREER (
  CAREER_ID        NUMBER GENERATED ALWAYS AS IDENTITY,
  PERSON_ID        NUMBER         NOT NULL,
  COMPANY_NAME     VARCHAR2(100)  NOT NULL,
  START_DATE       DATE           NOT NULL,
  END_DATE         DATE,
  POSITION_NAME    VARCHAR2(50),
  DUTY_DESC        VARCHAR2(500),
  CONSTRAINT PK_RSM_CAREER PRIMARY KEY (CAREER_ID),
  CONSTRAINT FK_RSM_CAREER_PERSON FOREIGN KEY (PERSON_ID) REFERENCES RSM_PERSON (PERSON_ID) ON DELETE CASCADE,
  CONSTRAINT CK_RSM_CAREER_PERIOD CHECK (END_DATE IS NULL OR END_DATE >= START_DATE)
);

COMMENT ON TABLE  RSM_CAREER               IS '경력사항';
COMMENT ON COLUMN RSM_CAREER.CAREER_ID     IS '경력ID';
COMMENT ON COLUMN RSM_CAREER.PERSON_ID     IS '인원ID';
COMMENT ON COLUMN RSM_CAREER.COMPANY_NAME  IS '회사명';
COMMENT ON COLUMN RSM_CAREER.START_DATE    IS '근무시작일';
COMMENT ON COLUMN RSM_CAREER.END_DATE      IS '근무종료일(NULL=재직중)';
COMMENT ON COLUMN RSM_CAREER.POSITION_NAME IS '직위';
COMMENT ON COLUMN RSM_CAREER.DUTY_DESC     IS '담당업무';

-- ---------------------------------------------------------------------
-- 5. 교육이수
-- ---------------------------------------------------------------------
CREATE TABLE RSM_TRAINING (
  TRAINING_ID      NUMBER GENERATED ALWAYS AS IDENTITY,
  PERSON_ID        NUMBER         NOT NULL,
  TRAINING_NAME    VARCHAR2(200)  NOT NULL,
  START_DATE       DATE,
  END_DATE         DATE,
  INSTITUTION      VARCHAR2(100),
  CONSTRAINT PK_RSM_TRAINING PRIMARY KEY (TRAINING_ID),
  CONSTRAINT FK_RSM_TRAINING_PERSON FOREIGN KEY (PERSON_ID) REFERENCES RSM_PERSON (PERSON_ID) ON DELETE CASCADE
);

COMMENT ON TABLE  RSM_TRAINING               IS '교육이수';
COMMENT ON COLUMN RSM_TRAINING.TRAINING_ID   IS '교육ID';
COMMENT ON COLUMN RSM_TRAINING.PERSON_ID     IS '인원ID';
COMMENT ON COLUMN RSM_TRAINING.TRAINING_NAME IS '교육명';
COMMENT ON COLUMN RSM_TRAINING.START_DATE    IS '시작일';
COMMENT ON COLUMN RSM_TRAINING.END_DATE      IS '종료일';
COMMENT ON COLUMN RSM_TRAINING.INSTITUTION   IS '기관';

-- ---------------------------------------------------------------------
-- 6. 보유기술 및 외국어능력
-- ---------------------------------------------------------------------
CREATE TABLE RSM_SKILL (
  SKILL_ID         NUMBER GENERATED ALWAYS AS IDENTITY,
  PERSON_ID        NUMBER         NOT NULL,
  SKILL_NAME       VARCHAR2(100)  NOT NULL,
  PROFICIENCY      CHAR(1),
  CONSTRAINT PK_RSM_SKILL PRIMARY KEY (SKILL_ID),
  CONSTRAINT FK_RSM_SKILL_PERSON FOREIGN KEY (PERSON_ID) REFERENCES RSM_PERSON (PERSON_ID) ON DELETE CASCADE,
  CONSTRAINT UK_RSM_SKILL UNIQUE (PERSON_ID, SKILL_NAME),
  CONSTRAINT CK_RSM_SKILL_PROF CHECK (PROFICIENCY IN ('A','B','C'))
);

COMMENT ON TABLE  RSM_SKILL             IS '보유기술 및 외국어능력';
COMMENT ON COLUMN RSM_SKILL.SKILL_ID    IS '기술ID';
COMMENT ON COLUMN RSM_SKILL.PERSON_ID   IS '인원ID';
COMMENT ON COLUMN RSM_SKILL.SKILL_NAME  IS '기술/외국어명';
COMMENT ON COLUMN RSM_SKILL.PROFICIENCY IS '숙련도(A/B/C)';

-- ---------------------------------------------------------------------
-- 7. 프로젝트 수행이력 (개발환경 포함)
-- ---------------------------------------------------------------------
CREATE TABLE RSM_PROJECT (
  PROJECT_ID       NUMBER GENERATED ALWAYS AS IDENTITY,
  PERSON_ID        NUMBER         NOT NULL,
  PROJECT_NAME     VARCHAR2(300)  NOT NULL,
  START_DATE       DATE,
  END_DATE         DATE,
  CLIENT_NAME      VARCHAR2(100),
  WORK_COMPANY     VARCHAR2(100),
  ROLE_NAME        VARCHAR2(50),
  ENV_MACHINE      VARCHAR2(100),
  ENV_OS           VARCHAR2(100),
  ENV_LANGUAGE     VARCHAR2(100),
  ENV_DBMS         VARCHAR2(100),
  ENV_TOOL         VARCHAR2(200),
  ENV_COMM         VARCHAR2(100),
  ENV_WAS          VARCHAR2(100),
  TASK_DESC        VARCHAR2(2000),
  CONSTRAINT PK_RSM_PROJECT PRIMARY KEY (PROJECT_ID),
  CONSTRAINT FK_RSM_PROJECT_PERSON FOREIGN KEY (PERSON_ID) REFERENCES RSM_PERSON (PERSON_ID) ON DELETE CASCADE,
  CONSTRAINT CK_RSM_PROJECT_PERIOD CHECK (END_DATE IS NULL OR END_DATE >= START_DATE)
);

COMMENT ON TABLE  RSM_PROJECT              IS '프로젝트 수행이력';
COMMENT ON COLUMN RSM_PROJECT.PROJECT_ID   IS '프로젝트ID';
COMMENT ON COLUMN RSM_PROJECT.PERSON_ID    IS '인원ID';
COMMENT ON COLUMN RSM_PROJECT.PROJECT_NAME IS '프로젝트명(시스템명)';
COMMENT ON COLUMN RSM_PROJECT.START_DATE   IS '참여시작일';
COMMENT ON COLUMN RSM_PROJECT.END_DATE     IS '참여종료일';
COMMENT ON COLUMN RSM_PROJECT.CLIENT_NAME  IS '고객사';
COMMENT ON COLUMN RSM_PROJECT.WORK_COMPANY IS '근무회사';
COMMENT ON COLUMN RSM_PROJECT.ROLE_NAME    IS '역할';
COMMENT ON COLUMN RSM_PROJECT.ENV_MACHINE  IS '개발환경-기종';
COMMENT ON COLUMN RSM_PROJECT.ENV_OS       IS '개발환경-OS';
COMMENT ON COLUMN RSM_PROJECT.ENV_LANGUAGE IS '개발환경-언어';
COMMENT ON COLUMN RSM_PROJECT.ENV_DBMS     IS '개발환경-DBMS';
COMMENT ON COLUMN RSM_PROJECT.ENV_TOOL     IS '개발환경-TOOL';
COMMENT ON COLUMN RSM_PROJECT.ENV_COMM     IS '개발환경-통신';
COMMENT ON COLUMN RSM_PROJECT.ENV_WAS      IS '개발환경-WAS';
COMMENT ON COLUMN RSM_PROJECT.TASK_DESC    IS '수행업무';

-- ---------------------------------------------------------------------
-- 8. 인덱스 (FK 조회용)
-- ---------------------------------------------------------------------
CREATE INDEX IX_RSM_EDUCATION_PERSON   ON RSM_EDUCATION   (PERSON_ID);
CREATE INDEX IX_RSM_CERTIFICATE_PERSON ON RSM_CERTIFICATE (PERSON_ID);
CREATE INDEX IX_RSM_CAREER_PERSON      ON RSM_CAREER      (PERSON_ID);
CREATE INDEX IX_RSM_TRAINING_PERSON    ON RSM_TRAINING    (PERSON_ID);
CREATE INDEX IX_RSM_PROJECT_PERSON     ON RSM_PROJECT     (PERSON_ID);

-- =====================================================================
-- 9. 이력서.docx 데이터 적재
--    - 문서의 빈칸/플레이스홀더(YYYY-MM-DD, '-')는 NULL 처리
--    - '재직중'은 END_DATE = NULL
-- =====================================================================
DECLARE
  v_pid RSM_PERSON.PERSON_ID%TYPE;
BEGIN
  INSERT INTO RSM_PERSON (PERSON_NAME, ADDRESS, ETC_SKILLS)
  VALUES ('홍길동', '경기도 화성시', 'CREO, AutoCAD, SolidWorks')
  RETURNING PERSON_ID INTO v_pid;

  -- 학력사항
  INSERT INTO RSM_EDUCATION (PERSON_ID, SCHOOL_NAME, MAJOR_NAME, ADMISSION_DATE, GRADUATION_DATE, GRAD_STATUS)
  VALUES (v_pid, 'OOO고등학교', '인문계 이과', DATE '2008-03-03', DATE '2011-02-09', '졸업');
  INSERT INTO RSM_EDUCATION (PERSON_ID, SCHOOL_NAME, MAJOR_NAME, ADMISSION_DATE, GRADUATION_DATE, GRAD_STATUS)
  VALUES (v_pid, 'OO대학교', 'XXX공학과', DATE '2011-03-02', DATE '2017-08-22', '졸업');

  -- 경력사항
  INSERT INTO RSM_CAREER (PERSON_ID, COMPANY_NAME, START_DATE, END_DATE, POSITION_NAME, DUTY_DESC)
  VALUES (v_pid, 'OOO', DATE '2019-04-01', DATE '2023-07-31', '대리', '기구설계 (CREO, AutoCAD)');
  INSERT INTO RSM_CAREER (PERSON_ID, COMPANY_NAME, START_DATE, END_DATE, POSITION_NAME, DUTY_DESC)
  VALUES (v_pid, 'OOOOO', DATE '2023-08-03', DATE '2024-09-30', '선임', '기구설계 (CREO, AutoCAD)');
  INSERT INTO RSM_CAREER (PERSON_ID, COMPANY_NAME, START_DATE, END_DATE, POSITION_NAME, DUTY_DESC)
  VALUES (v_pid, 'OOOOOO', DATE '2024-10-28', NULL, '선임', '공정물류 기구설계');

  -- 보유기술
  INSERT INTO RSM_SKILL (PERSON_ID, SKILL_NAME, PROFICIENCY) VALUES (v_pid, 'AutoCAD',    'A');
  INSERT INTO RSM_SKILL (PERSON_ID, SKILL_NAME, PROFICIENCY) VALUES (v_pid, 'CREO',       'B');
  INSERT INTO RSM_SKILL (PERSON_ID, SKILL_NAME, PROFICIENCY) VALUES (v_pid, 'SolidWorks', 'B');

  -- 프로젝트 수행이력
  INSERT INTO RSM_PROJECT (PERSON_ID, PROJECT_NAME, START_DATE, END_DATE, CLIENT_NAME, WORK_COMPANY, ROLE_NAME, ENV_TOOL, TASK_DESC)
  VALUES (v_pid, 'LGD 파주공장 애플워치 셀자동화검사장비 구축 1단계', DATE '2019-09-01', DATE '2019-12-31',
          'LGD', '소닉스', '설계', 'CREO, AutoCAD', 'CAMERA 파트 설계, 프레임 설계');
  INSERT INTO RSM_PROJECT (PERSON_ID, PROJECT_NAME, START_DATE, END_DATE, CLIENT_NAME, WORK_COMPANY, ROLE_NAME, ENV_TOOL, TASK_DESC)
  VALUES (v_pid, 'LGD 파주공장 애플워치 셀자동화검사장비 구축 2단계', DATE '2020-09-01', DATE '2020-12-31',
          'LGD', '소닉스', '설계', 'CREO, AutoCAD', 'CAMERA 파트 설계, 프레임 설계');
  INSERT INTO RSM_PROJECT (PERSON_ID, PROJECT_NAME, START_DATE, END_DATE, CLIENT_NAME, WORK_COMPANY, ROLE_NAME, ENV_TOOL, TASK_DESC)
  VALUES (v_pid, 'LGD 파주공장 애플워치 셀 자동화 검사장비 구축 3단계', DATE '2021-09-01', DATE '2021-12-31',
          'LGD', '소닉스', '설계', 'CREO, AutoCAD', 'CAMERA 파트 설계, 프레임 설계');

  COMMIT;
END;
/
